#!/usr/bin/env sh
chown -R flexget:flexget \
	/mnt/flexget \
	/var/log/flexget
chown -R openvpn:openvpn \
	/mnt/openvpn \
	/var/log/openvpn
chown -R transmission:transmission \
	/mnt/torrent \
	/mnt/transmission \
	/var/log/transmission
